#!/bin/sh -e

export PACKAGE="dependency"
export PREFIX=""
if [ -d 'venv' ] ; then
    export PREFIX="venv/bin/"
fi

set -x

PYTHONPATH=. ${PREFIX}pytest --ignore venv --ignore examples --cov=${PACKAGE} --cov=tests --cov-report=term-missing ${@}
${PREFIX}coverage html
